# Generated by Django 3.2.5 on 2021-07-03 19:05

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend.models.auto_code_generator, max_length=8, unique=True),
        ),
    ]
